function extend(b,c){for(var e in c)b[e]=c[e];return b}function $_(b,c,e){b=document.getElementById(b);if(!b)return null;if(c)for(var f in c)f.indexOf(".")==0?b.style[f.replace(/^./,"")]=c[f]:b[f]=c[f];e&&e.appendChild(b);return $fix(b)}
function $fix(b,c,e){b=extend(b,{$T:function(b){return this.getElementsByTagName(b)},$B:function(b){for(var c in b)c.indexOf(".")==0?this.style[c.replace(/^./,"")]=b[c]:this[c]=b[c];return this},empty:function(){for(;this.firstChild;)this.removeChild(this.firstChild);return this},isChildNodeOf:function(b){for(var c=false,e=this;e.parentNode&&!c;)e.parentNode==b?c=true:e=e.parentNode;return c},outerHeight:function(){window.getComputedStyle(this,null);return this.offsetHeight},innerHeight:function(){var b=
window.getComputedStyle(this,null);return this.offsetHeight-parseInt(b.paddingTop)-parseInt(b.paddingBottom)-parseInt(b.borderTopWidth)-parseInt(b.borderBottomWidth)},outerWidth:function(){window.getComputedStyle(this,null);return this.offsetWidth},innerWidth:function(){var b=window.getComputedStyle(this,null);return this.offsetWidth-parseInt(b.paddingLeft)-parseInt(b.paddingRight)-parseInt(b.borderLeftWidth)-parseInt(b.borderRightWidth)}});if(c)for(var f in c)f.indexOf(".")==0?b.style[f.replace(/^./,
"")]=c[f]:b[f]=c[f];e&&e.appendChild(b);return b}
function $A(b){if(!b)return[];if(b.toArray)return b.toArray();for(var c=b.length||0,e=Array(c);c--;)e[c]=b[c];return e=extend(e,{append:function(b){for(var c=0;c<b.length;c++)this.push(b[c]);return this},remove:function(b){for(var c=0;c<this.length;c++)this[c]==b&&this.splice(c,1)},each:function(b){for(var c=0;c<this.length;c++)b.call(this,this[c],c)},empty:function(){this.splice(0,this.length);return this},find:function(b){for(var c=0;c<this.length;c++)if(this[c]==b)return c;return-1},cleanEmptyValues:function(){for(var b=
0;b<this.length;b++)this[b]==""&&this.splice(b,1);return this},values:function(){for(var b=[],c=0;c<this.length;c++)b.push(this[c]);return b}})}function $C(b,c,e){b=document.createElement(b);return $fix(b,c,e)}function $T(b,c){return c?c.getElementsByTagName(b):document.getElementsByTagName(b)}
extend(Function.prototype,{argumentNames:function(){var b=this.toString().match(/^[\s\(]*function[^(]*\(([^\)]*)\)/)[1].replace(/\s+/g,"").split(",");return b.length==1&&!b[0]?[]:b},bind:function(){if(arguments.length<2&&typeof arguments[0]=="undefined")return this;var b=this,c=$A(arguments),e=c.shift();return function(){return b.apply(e,c.concat($A(arguments)))}}});function $capitalize(b){return b.replace(/\w+/g,function(b){return b.charAt(0).toUpperCase()+b.slice(1).toLowerCase()})}
function $clone(b){if(b==null||typeof b!="object")return b;var c=b.constructor(),e;for(e in b)c[e]=clone(b[e]);return c}function $execWhenExists(b,c){if(typeof window[b]!="function"){var e="launcher_"+b+Math.floor(Math.random()*1E4);$T("BODY")[0][e]=window.setInterval(function(){typeof window[b]=="function"&&(c(),window.clearInterval($T("BODY")[0][e]))},100)}else c()}
function $execWhenTrue(b,c){if(eval(b))c();else{var e="launcher_"+b+Math.floor(Math.random()*1E4);$T("BODY")[0][e]=window.setInterval(function(){eval(b)&&(c(),window.clearInterval($T("BODY")[0][e]))},100)}}function $each(b,c){if($type(b)=="object"){var e=0,f;for(f in b)c.call(this,f,b[f],e),e++}}function $getElementStyle(b,c){if(b.currentStyle)return b.currentStyle[c];if(window.getComputedStyle)return document.defaultView.getComputedStyle(b,null).getPropertyValue(c)}
function $getOffsetLeft(b){for(var c=0;b.parentNode;)c+=b.offsetLeft-parseInt($getElementStyle(b,"padding-left")),b=b.parentNode;return c}function $getOffsetTop(b){for(var c=0;b.parentNode;)c+=b.offsetTop-parseInt($getElementStyle(b,"padding-top")),b=b.parentNode;return c}function $getOffsetPosition(b){return b.getBoundingClientRect()}function $htmlEntitiesDecode(b){return!b?"":b.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">")}
function $htmlEntitiesEncode(b){return!b?"":b.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/\\/g,"")}function $parseForm(b){var c={};$A(b.$T("INPUT")).append(b.$T("TEXTAREA")).append(b.$T("SELECT")).each(function(b){if(b.type=="checkbox")c[b.name]=b.checked;else if(b.type!="radio"||b.checked)c[b.name]=b.value});return c}function $reAltElements(b){var c="";$A(b.childNodes).each(function(b){b.className=b.className.replace(/[ ]*alt[ ]*/,"")+c;c=c==""?" alt":""});b.alt=c}
function $round(b){b=b.toString();if(b.indexOf(".")==-1)return b;b=(parseFloat(b)*1E3).toString().split(".")[0];parseInt(b[b.length-1])>4&&(b=b[0]!="-"?(parseInt(b)+10).toString():(parseInt(b)-10).toString());b=(parseInt(b)/10).toString();b=b.split(".")[0];return b=(parseInt(b)/100).toString()}function $toUrl(b){var c="",e;for(e in b)c+=e+"="+(b[e].toString().match(/\&/)?escape(b[e].toString()):b[e].toString())+"&";return c.replace(/&$/,"")}function $type(b){return typeof b}
function isEmpty(b){return!b||b==""?true:false}function print_r(b,c){var e="";c?c+="    ":c="    ";if(b.constructor==Array||b.constructor==Object)for(var f in b)e+=b[f]?b[f].constructor==Array||b[f].constructor==Object?c+"["+f+"] => "+(b[f].constructor==Array?"Array":"Object")+"\n"+c+"(\n"+print_r(b[f],c)+c+")\n":c+"["+f+"] => "+b[f]+"\n":c+"["+f+"] => NULL\n";return e}function jsonEncode(b){if(JSON.stringify)return JSON.stringify(b)}
function jsonDecode(b){if(isEmpty(b))return{errorCode:999,errorDescription:"La cadena est\u00e1 vac\u00eda, revise la API o el COMANDO"};if(b.match("<title>404 Not Found</title>"))return{errorCode:999,errorDescription:"La URL de la API es err\u00f3nea: 404"};if(!JSON||!JSON.parse)return eval("("+b+")");try{return JSON.parse(b)}catch(c){return{errorCode:999,errorDescription:b}}}
function jsonClassEncode(b){var c="";b.constructor==Array&&(c+="[");b.constructor==Object&&(c+="{");for(var e in b)b[e]?(b[e]=="[object HTMLDivElement]"&&!isEmpty(b[e].id)&&(b[e]="$_('"+b[e].id+")"),c+=b[e].constructor==Array||b[e].constructor==Object?"'"+e+"':"+jsonClassEncode(b[e])+",":"'"+e+"':"+JSON.stringify(b[e].toString())+","):c+="'"+e+"':NULL,";c=c.replace(/,$/,"");b.constructor==Array&&(c+="]");b.constructor==Object&&(c+="}");return c}
function include_once(b,c){if(c)var e=c;else if(e=b.match(/(css|js)$/))e=e[1];else return;var f=e.replace(/js/i,"script").replace(/css/i,"link");b.match(/[^\/]*$/);var g=false;$A($fix($T("HEAD")[0]).$T(f.toUpperCase())).each(function(c){if(c.src&&c.src==b||c.href&&c.href==b)g=true});g||eval("include"+e.toUpperCase()+"('"+b+"');")}function includeJS(b){return $C("SCRIPT",{src:b,type:"text/javascript"},$T("head")[0])}
function includeCSS(b){return $C("LINK",{href:b,rel:"stylesheet",type:"text/css"},$T("head")[0])}function cookieTake(b){return(b=document.cookie.match("(?:^|;)\\s*"+b.replace(/([-.*+?^${}()|[\]\/\\])/g,"\\$1")+"=([^;]*)"))?b[1]:b}function cookieSet(b,c,e){var f=new Date;f.setDate(f.getDate()+e);document.cookie=b+"="+escape(c)+(e==null?"":";expires="+f.toGMTString()+";path=/")}function cookieRemove(b){document.cookie=b+"=;expires=Thu, 01-Jan-1970 00:00:01 GMT;"}
function cookiesToObj(){var b=document.cookie.replace(/;[ ]?/g,";").split(";");if(isEmpty(b))return{};var c={};$A(b).each(function(b){b=b.match(/([^=]*)=(.*)/);c[unescape(b[1])]=unescape(b[2])});return c}function cookiesToArr(){var b=document.cookie.replace(/;[ ]?/g,";").split(";");if(isEmpty(b))return[];var c=[];$A(b).each(function(b){b=b.match(/([^=]*)=(.*)/);c.push({cookieName:unescape(b[1]),cookieValue:unescape(b[2])})});return c}var TEMPLATES={};
function $downloadTemplate(b,c){TEMPLATES[b]?c(TEMPLATES[b]):ajaxPetition(b,"",function(e){TEMPLATES[b]=e.responseText;c(e.responseText)})}var Class=function(b){var c=function(){var b=$clone(this);b.init.apply(b,arguments);return b};c.prototype=$clone(b);return c};function clone(b){return $clone(b)}
function ajaxObject(){var b=false;try{b=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){try{b=new ActiveXObject("Microsoft.XMLHTTP")}catch(e){b=false}}!b&&typeof XMLHttpRequest!="undefined"&&(b=new XMLHttpRequest);return b}
function ajaxPetition(b,c,e,z){if(b){c||(c="");var f="GET";b.match(/\.php$/)&&(f="POST");if(z){f=z;}var g=Math.floor(Math.random()*1E4),h=new ajaxObject;h.open(f,b+"?rnd="+g,true);h.onreadystatechange=function(){h.readyState==4&&e(h)};h.setRequestHeader("Content-Type","application/x-www-form-urlencoded");h.send(c)}}var VAR_apps={},VAR_appsPath="resources/apps/";
function launchApp(b,c,e,f){f=f?f:VAR_appsPath;if(VAR_apps[b])VAR_apps[b].init(c,e);else{for(a in{js:null,css:null})include_once(f+b+"/index."+a,a);$execWhenTrue("!isEmpty(window['"+b+"'])",function(){VAR_apps[b]=new window[b](c,e?e:null)})}}var VAR_schedules={},VAR_schedulerRun=false,VAR_schedulerDelay=1E4;function schedulerAdd(b,c){VAR_schedules[b]=c}function schedulerExec(){if(VAR_schedulerRun)for(var b in VAR_schedules)VAR_schedules[b]()}
function schedulerRun(b){VAR_schedulerRun=b?true:false}function schedulerRestart(){clearInterval(window.scheduler);window.scheduler=setInterval(schedulerExec,VAR_schedulerDelay)}window.scheduler=setInterval(schedulerExec,VAR_schedulerDelay);
function createThemeWindow(b){if($_("wod_"+b))return $_("wod_"+b);var c=$C("DIV",{className:"wodTheme",id:"wod_"+b}),e=$C("DIV",{className:"wodThemeHeaderLeft"},c),e=$C("DIV",{className:"wodThemeHeaderRight"},e);$C("DIV",{className:"wodThemeHeaderCenter"},e);e=$C("DIV",{className:"wodThemeContainerLeft"},c);e=$C("DIV",{className:"wodThemeContainerRight"},e);$C("DIV",{className:"wodThemeContainerCenter",id:"wod_"+b+"_container",".position":"relative"},e);e=$C("DIV",{className:"wodThemeFooterLeft"},
c);e=$C("DIV",{className:"wodThemeFooterRight"},e);$C("DIV",{className:"wodThemeFooterCenter"},e);return c}function window_destroy(b,c){for(;b.parentNode&&b.className!="wodTheme";)b=b.parentNode;if(b.parentNode){var e=function(){};if(b.afterRemove)e=b.afterRemove;b.parentNode.removeChild(b);c&&c.stopPropagation();e()}}var VAR_wodInfo={zIndex:40,marginRight:1};
function info_create(d,a,b,c){var e=$_("info_"+d);if(e)return b&&b.appendChild(e),e;a||(a={});extend(a,{id:"info_"+d,className:"wodInfo",onclick:function(a){a.stopPropagation()},".zIndex":VAR_wodInfo.zIndex++});b||(b=$T("BODY")[0]);a=$C("DIV",a,b);b=a.infoIndicator=$C("DIV",{className:"wodInfoIndicator"},a);b=$C("DIV",{className:"wodInfoHeaderLeft"},a);b=$C("DIV",{className:"wodInfoHeaderRight"},b);$C("DIV",{className:"wodInfoHeaderCenter"},b);b=$C("DIV",{className:"wodInfoContainerLeft"},a);b=$C("DIV", {className:"wodInfoContainerRight"},b);a.infoContainer=$C("DIV",{className:"wodInfoContainerCenter",infoWindow:a,id:"info_"+d+"_container",".position":"relative"},b);b=$C("DIV",{className:"wodInfoFooterLeft"},a);b=$C("DIV",{className:"wodInfoFooterRight"},b);$C("DIV",{className:"wodInfoFooterCenter"},b);c=c?c:10;"center"!=c&&(0>c&&(c=a.offsetWidth+c),c+="px");a.infoIndicator.style.backgroundPosition=c+" top";d=$getOffsetPosition(a);d=$T("BODY")[0].offsetWidth-d.left-d.width;d<VAR_wodInfo.marginRight&& (a.style.left=a.offsetLeft+d-VAR_wodInfo.marginRight+"px",a.infoIndicator.style.backgroundPosition=parseInt(c)+-1*d+VAR_wodInfo.marginRight+"px top");return a};
function info_destroy(b,c){for(;b.parentNode&&b.className!='wodInfo';)b=b.parentNode;if(b.parentNode){if(b.parentNode.className.match(/ pressed$/))b.parentNode.className=b.parentNode.className.replace(/ pressed$/,"");var e=function(){};if(b.afterRemove)e=b.afterRemove;b.parentNode.removeChild(b);c&&c.stopPropagation();e()}}
function info_transition(b,c){var e=b.parentNode;e.$B({".overflow":"hidden"});c.$B({".position":"absolute",".top":"0",".left":"0",".width":b.innerWidth()+"px"});e.appendChild(c);e.parentNode.infoContainer=c;b.innerHeight();c.innerHeight();eEaseHeight(e,c.offsetHeight,function(b){b.$B({".height":"100%"})},1250,false,true);eFadeout(b,function(b){b.parentNode.removeChild(b)});eFadein(c,function(b){b.$B({".position":"static",".top":"auto",".left":"auto",".width":"auto"})})}
function info_loader(b,c){var e=$C("DIV",{className:"wodInfoContainer loading"});$C("SPAN",{innerHTML:c},e);info_transition(b.infoContainer,e)}function createGnomeButton(b,c,e){return gnomeButton_create(b,c,false,e)}
function gnomeButton_create(b,c,e,f){f||(f="gnomeButton");if(e&&e.tagName=="UL")return gnomeButton_create_li(b,c,e,f);var g=d=$C("DIV",{className:"button "+f+"Unpressed"});g.buttonContainer=d=$C("DIV",{className:"buttonCenter",innerHTML:b},$C("DIV",{className:"buttonRight"},$C("DIV",{className:"buttonLeft"},d)));g.onmousedown=function(b){b.preventDefault();g.className=g.className.replace(f+"Unpressed",f+"Pressed")};g.onmouseup=d.onmouseout=function(){g.className=g.className.replace(f+"Pressed",f+
"Unpressed")};g.onclick=function(b){c(b,g)};e&&e.appendChild(g);return g}function gnomeButton_create_li(b,c,e,f){f||(f="gnomeButton");f=$C("LI",{className:"button "+f,onclick:function(b){c(b,this)}});f.buttonContainer=$C("DIV",{className:"buttonCenter",innerHTML:b},f);e&&e.appendChild(f);return f}
function eTweenStart(b,c){c||(c=50);b.eTween&&window.clearInterval(b.eTween);b.eTweenMode="decr";b.fvalue=1;b.eTween=window.setInterval(function(){fvalue=b.eTweenMode=="incr"?parseFloat(b.fvalue)+0.11+"".substring(0,3):parseFloat(b.fvalue)-0.11+"".substring(0,3);if(fvalue>0.9)fvalue=1,b.eTweenMode="decr";if(fvalue<0.1)fvalue=0,b.eTweenMode="incr";b.style.opacity=b.fvalue=fvalue},c)}
function eTweenStop(b,c){c||(c=50);b.eTween&&window.clearInterval(b.eTween);fvalue=parseFloat(b.fvalue);b.eTween=window.setInterval(function(){fvalue=parseFloat(b.fvalue)+0.11+"".substring(0,3);if(fvalue>0.9)fvalue=1,b.style.opacity=b.fvalue=fvalue,window.clearInterval(b.eTween),b.eTween=false;b.style.opacity=b.fvalue=fvalue},c)}
function eFadein(b,c,e){e||(e=50);var f=0;if(b.eFade)window.clearInterval(b.eFade),b.eFade=false,f=b.style.opacity?b.style.opacity:0;b.style.visibility="visible";b.style.opacity=b.fvalue=f;b.eFade=window.setInterval(function(){f=parseFloat(b.fvalue)+0.11+"".substring(0,3);b.style.opacity=b.fvalue=f;if(f>0.9)b.style.opacity=b.fvalue=1,window.clearInterval(b.eFade),b.eFade=false,c&&c(b)},e)}
function eFadeout(b,c,e){e||(e=50);var f=1;if(b.eFade)window.clearInterval(b.eFade),b.eFade=false,f=b.style.opacity?b.style.opacity:1;b.style.opacity=b.fvalue=f;b.eFade=window.setInterval(function(){f=parseFloat(b.fvalue)-0.11+"".substring(0,3);b.style.opacity=b.fvalue=f;if(f<0.1)b.style.visibility="hidden",b.style.opacity=b.fvalue=0,window.clearInterval(b.eFade),b.eFade=false,c&&c(b)},e)}function easeInOutCubic(b,c,e,f){return(b/=f/2)<1?e/2*b*b*b+c:e/2*((b-=2)*b*b+2)+c}
function eEaseHeight(b,c,e,f,g,h){f||(f=1E3);g||(g=50);if(b.eEaseH)window.clearInterval(b.eEaseH),b.eEaseH=false;b.innerHeight||$fix(b);var i=b.innerHeight(),j=0;if(h&&(c-=i,c==0))return;b.eEaseH=window.setInterval(function(){var h=easeInOutCubic(j,i,c,f);j+=g;b.style.height=h+"px";if(j>=f)b.style.height=i+c+"px",window.clearInterval(b.eEaseH),b.eEaseH=false,e&&e(b)},f/g)}
function eEaseWidth(b,c,e,f,g,h){f||(f=1E3);g||(g=50);if(b.eEaseW)window.clearInterval(b.eEaseW),b.eEaseW=false;b.innerWidth||$fix(b);var i=b.innerWidth(),j=0;if(h&&(c-=i,c==0))return;b.eEaseW=window.setInterval(function(){var h=easeInOutCubic(j,i,c,f);j+=g;b.style.width=h+"px";if(j>=f)b.style.width=i+c+"px",window.clearInterval(b.eEaseW),b.eEaseW=false,e&&e(b)},f/g)};
